// Copyright (c) Pho Tue SoftWare Solutions JSC.
// Licensed under the MIT license.

import "IAppearanceConfig.idl";

namespace Microsoft.Terminal.Settings.Model
{
    runtimeclass AppearanceConfig : [default] IAppearanceConfig {
    }
}
