// Copyright (c) Pho Tue SoftWare Solutions JSC.
// Licensed under the MIT license.

namespace SampleApp
{
    [default_interface] runtimeclass MyPage : Windows.UI.Xaml.Controls.Page
    {
        MyPage();
    }
}
