// Copyright (c) Pho Tue SoftWare Solutions JSC.
// Licensed under the MIT license.


namespace SampleApp
{

    [default_interface] runtimeclass SampleAppLogic
    {
        SampleAppLogic();

        void Create();

        Windows.UI.Xaml.UIElement GetRoot();

        String Title { get; };

    }
}
